### PR TITLE
Add related links to README

### PR DESCRIPTION
**Pull request by RobertHerhold**
I recently created a [Joi port](https://github.com/RobertHerhold/boolean-json-joi-schema) of this library. I think it would be useful for developers also using Joi to find it more easily. I have also linked back to this library on my package.

### CODE REVIEW

**Comment by kemitchell** [comment]
I wasn't aware of your Joi work!

As for `README`, I'm certainly not against letting others know that more is available. But I imagine we could both make better use of our time than manually tending a plain-text list.

I believe all the original `boolean-json` packages share a common package name prefix.  Many have a `boolean-json` npm keyword, as well, and it would be easy enough to go back and tag any that I missed.  You might do the same.

Why not a link to [the package-name prefix](https://www.npmjs.com/search?q=boolean-json-) or [the keyword](https://www.npmjs.com/browse/keyword/boolean-json)?

**Comment by RobertHerhold** [comment]
Whichever is fine with me - however, I think it would be easy to have a lot of unrelated packages show up

**Comment by kemitchell** [comment]
Anyone can add a `boolean-json` keyword or use a package name with `boolean-json-`, but in practice, that kind of thing almost never happens. If it did, the cost is trifling.

**Comment by RobertHerhold** [comment]
@kemitchell That's fine with me - I edited my PR to simply link the NPM registry.

**Pull request closed without merging**
